image: python:3.12.3

stages:
  - test

variables:
  PYTHON_VERSION: "3.12.3"
  COVERAGE_DIR: "coverage_reports"

before_script:
  - python -m pip install --upgrade pip
  - pip install -r requirements.txt

test:
  stage: test
  script:
    - pytest --cov=app --cov=model --cov=ticket --cov=${COVERAGE_DIR}/coverage.xml --cov-report=term-missing
  artifacts:
    paths:
      - ${COVERAGE_DIR}/coverage.xml
    expire_in: 1 week

  coverage: '/TOTAL\s+\d+\s+\d+\s+(\d+%)/'

  only:
    - main
